---
# TODO - comment on iterative nature of this file

- name: CLIENT | Check if client key already exists
  stat:
    path: "{{ openvpn_folder_ca_root }}/keys/{{ client.name }}.key"
  register: stat_result

- name: CLIENT | Generate client certificate and key
  when: stat_result.stat.exists == False
  block:
    - name: CLIENT | Generate client key
      shell: |
        source ./vars && ./build-key --batch {{ client.name }}
      args:
        executable: /bin/bash
        chdir: "{{ openvpn_folder_ca_root }}"
     
    - name: CLIENT | Override client pass
      when: False
      shell: |
        source ./vars && ./build-key-pass --batch {{ client.name }}
      args:
        executable: /bin/bash
        chdir: "{{ openvpn_folder_ca_root }}"
