---
- name: CLIENT | Ensure client config directory strucure
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - "{{ openvpn_folder_client_root }}"
    - "{{ openvpn_folder_client_files }}"

- name: CLIENT | Copy client base.conf 
  template:
    src: base.conf.j2
    dest: "{{ openvpn_folder_client_root }}/base.conf"
    owner: root
    group: root
    mode: 0600

- name: CLIENT | Copy make_config script
  template:
    src: make_config.sh.j2
    dest: "{{ openvpn_folder_client_root }}/make_config.sh"
    owner: root
    group: root
    mode: 0700
